nodeLinker: pnp

packageExtensions:
  nestjs-pino@*:
    dependencies:
      pino: "*"
      rxjs: "*"
  "@nestjs-modules/mailer@*":
    dependencies:
      tslib: "*"
      lodash: "*"
      nodemailer: "*"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
