import {StyleSheet} from 'react-native';
import {BACKGROUND_WIDTH, BACKGROUND_HEIGHT} from '../constants/canvas';

export const styles = StyleSheet.create({
  editorContainer: {
    flex: 1,
    width: '100%',
    backgroundColor: 'white',
  },
  hiddenCanvas: {
    position: 'absolute',
    top: -9999,
    left: -9999,
    width: parseInt(BACKGROUND_WIDTH),
    height: parseInt(BACKGROUND_HEIGHT),
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  canvas: {
    width: '100%',
    height: '100%',
    backgroundColor: '#fff',
    position: 'relative',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  backButton: {
    padding: 8,
    marginRight: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  titleInputContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    width: '100%',
    backgroundColor: '#fff',
  },
  titleInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 8,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  saveButton: {
    color: '#1a73e8',
    fontSize: 16,
    fontWeight: '600',
  },
  canvasContainer: {
    flex: 1,
    margin: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemsContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  toolbar: {
    flexDirection: 'row',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  toolButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  deleteButton: {
    backgroundColor: '#ffe5e5',
  },
  textStyleControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  imageControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingVertical: 12,
    paddingHorizontal: 8,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  imageControlButton: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#f5f5f5',
  },
  imageControlButtonDisabled: {
    opacity: 0.5,
  },
  imageControlText: {
    marginTop: 4,
    fontSize: 12,
    color: '#666',
  },
  deleteText: {
    color: '#ff4444',
  },
  doneText: {
    color: '#1a73e8',
  },
  textStyleScrollView: {
    flex: 1,
    marginRight: 8,
  },
  textControlsRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  colorPickerModal: {
    position: 'absolute',
    bottom: '100%',
    left: 0,
    right: 0,
    backgroundColor: 'white',
    padding: 16,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  colorPickerContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
  },
  colorButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  colorButtonActive: {
    backgroundColor: '#e3f2fd',
  },
  colorPreview: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  textSizeControls: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 24,
    padding: 8,
  },
  textSizeValue: {
    marginHorizontal: 8,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#666',
    minWidth: 24,
    textAlign: 'center',
  },
  textControlButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f5f5f5',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 4,
  },
  textControlButtonActive: {
    backgroundColor: '#e3f2fd',
  },
  editorText: {
    minWidth: 100,
    minHeight: 30,
    padding: 8,
    textAlignVertical: 'top',
  },
  editorImage: {
    width: '100%',
    height: '100%',
    maxWidth: 300,
    maxHeight: 300,
    aspectRatio: 1,
  },
  backgroundImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    borderRadius: 8,
    objectFit: 'cover',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 16,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 16,
  },
  colorControls: {
    marginBottom: 16,
  },
  colorLabel: {
    fontSize: 14,
    color: '#666',
    marginBottom: 8,
  },
  imageSelectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8,
  },
  imageSelectText: {
    marginLeft: 8,
    fontSize: 16,
    color: '#666',
  },
});
